
import { AgreementDetails, PromoterType, AllotteeType, ProjectType } from "./types";

export const emptyAgreement: AgreementDetails = {
  executionDate: new Date().toISOString().split("T")[0],
  executionPlace: "",
  promoter: {
    type: PromoterType.INDIVIDUAL,
    companyName: "",
    cin: "",
    companiesActYear: "2013",
    registeredOffice: "",
    pan: "",
    authorizedSignatoryName: "",
    signatoryAadhaar: "",
    boardResolutionDate: "",
    partnershipName: "",
    partnershipRegAct: "1932",
    principalBusinessPlace: "",
    authorizedPartnerName: "",
    partnerAadhaar: "",
    partnerAuthorizedVide: "",
    individualName: "",
    individualAadhaar: "",
    parentName: "",
    age: "",
    residenceAddress: ""
  },
  allottee: {
    type: AllotteeType.INDIVIDUAL,
    companyName: "",
    cin: "",
    companiesActYear: "2013",
    registeredOffice: "",
    pan: "",
    authorizedSignatoryName: "",
    signatoryAadhaar: "",
    boardResolutionDate: "",
    partnershipName: "",
    partnershipRegAct: "1932",
    principalBusinessPlace: "",
    authorizedPartnerName: "",
    partnerAadhaar: "",
    partnerAuthorizedVide: "",
    individualName: "",
    individualAadhaar: "",
    parentName: "",
    age: "",
    residenceAddress: "",
    hufKartaName: "",
    hufKartaAadhaar: "",
    hufKartaParent: "",
    hufKartaAge: "",
    hufFamilyName: "",
    hufBusinessPlace: "",
    hufPan: ""
  },
  otherAllotteesText: "",
  landOwnerType: "ABSOLUTE",
  surveyNumbers: "",
  totalAdmeasuringSqM: "",
  tehsilAndDistrict: "",
  titleDeedDetails: "",
  subRegistrarOffice: "",
  collaborationAgreementDetails: "",
  projectType: ProjectType.RESIDENTIAL_MULTISTORIED,
  projectComprising: "",
  otherComponents: "",
  projectName: "",
  commencementAuthority: "",
  commencementDate: "",
  commencementBearingNo: "",
  layoutPlanAuthority: "",
  layoutPlanDate: "",
  reraRegOfficePlace: "Trivandrum",
  reraRegDate: "",
  reraRegistrationNumber: "",
  unitNo: "",
  unitAllocatedDate: "",
  unitAllottedNo: "",
  carpetAreaSqFt: "",
  unitTypeDescription: "",
  floorNo: "",
  towerOrBlock: "",
  garageClosedParkingNo: "1",
  parkingDetailsText: "",
  commonAreasProRataShare: "",
  totalPriceRupees: "",
  totalPriceWords: "",
  ratePerSqFt: "",
  breakdownCostCommonAreas: "",
  breakdownParkingPrice: "",
  breakdownTaxes: "",
  breakdownPreferentialCharges: "",
  bookingAmountRupees: "",
  bookingAmountWords: "",
  escrowAccountDetails: "",
  rebateRatePercent: "",
  consecutiveDemandsLimit: "",
  consecutiveMonthsLimit: "",
  offeredPossessionDays: "",
  outsideAreasFacilities: "",
  outsideCompetentAuthority: "",
  outsideStateActName: "",
  stateActLaws: "",
  customAgreementTerms: "",
  priceTableRows: [],
  garageParkingRows: [],
  plotTableRows: [],
  promoterPhoto: "",
  allotteePhoto: "",
  jointAllotteePhoto: "",
  promoterSignature: "",
  allotteeSignature: "",
  jointAllotteeSignature: "",
  witness1Signature: "",
  witness2Signature: "",
  additionalDisclosures: "",
  possessionDeadlineDate: "",
  stateApartmentActName: "Kerala Apartment Ownership Act, 1983",
  keralaStampActComplianceConfirmed: false
};

export const sampleCorporateFlat: AgreementDetails = {
  executionDate: "2026-06-15",
  executionPlace: "Kochi",
  promoter: {
    type: PromoterType.COMPANY,
    companyName: "Malabar Heights Builders Private Limited",
    cin: "U45201KL2015PTC038921",
    companiesActYear: "2013",
    registeredOffice: "Malabar Towers, 3rd Floor, M.G. Road, Ernakulam, Kerala - 682011",
    pan: "AABCM4592L",
    authorizedSignatoryName: "Jayadas Balakrishnan",
    signatoryAadhaar: "4512-8921-3301",
    boardResolutionDate: "2026-04-10",
    partnershipName: "",
    partnershipRegAct: "",
    principalBusinessPlace: "",
    authorizedPartnerName: "",
    partnerAadhaar: "",
    partnerAuthorizedVide: "",
    individualName: "",
    individualAadhaar: "",
    parentName: "",
    age: "",
    residenceAddress: ""
  },
  allottee: {
    type: AllotteeType.INDIVIDUAL,
    companyName: "",
    cin: "",
    companiesActYear: "",
    registeredOffice: "",
    pan: "BUPPK8091H",
    authorizedSignatoryName: "",
    signatoryAadhaar: "",
    boardResolutionDate: "",
    partnershipName: "",
    partnershipRegAct: "",
    principalBusinessPlace: "",
    authorizedPartnerName: "",
    partnerAadhaar: "",
    partnerAuthorizedVide: "",
    individualName: "Rajesh Kumar Pillai",
    individualAadhaar: "5541-0982-1273",
    parentName: "Sreedharan Pillai",
    age: "42",
    residenceAddress: "Nandanam House, Pattom P.O., Trivandrum, Kerala - 695004",
    hufKartaName: "",
    hufKartaAadhaar: "",
    hufKartaParent: "",
    hufKartaAge: "",
    hufFamilyName: "",
    hufBusinessPlace: "",
    hufPan: ""
  },
  otherAllotteesText: "Sobha Rajesh (Wife, Aadhaar: 5541-0982-9912)",
  landOwnerType: "ABSOLUTE",
  surveyNumbers: "Survey Nos. 104/2, 104/3A, and 105/1",
  totalAdmeasuringSqM: "4250.75",
  tehsilAndDistrict: "Kanayannur Taluk, Ernakulam District",
  titleDeedDetails: "Sale Deed dated 12th February 2018 registered as Doc No. 1024/2018",
  subRegistrarOffice: "Sub-Registrar Office, Ernakulam",
  collaborationAgreementDetails: "",
  projectType: ProjectType.RESIDENTIAL_MULTISTORIED,
  projectComprising: "multistoried premium residential towers consisting of 2BHK/3BHK Luxury Flats",
  otherComponents: "swimming pool, health club, and rooftop gathering spaces",
  projectName: "Malabar Magnolia Residency",
  commencementAuthority: "Kochi Municipal Corporation",
  commencementDate: "2024-03-15",
  commencementBearingNo: "KCP/CC/892/2024",
  layoutPlanAuthority: "Kochi Municipal Corporation",
  layoutPlanDate: "2024-01-20",
  reraRegOfficePlace: "Thiruvananthapuram",
  reraRegDate: "2024-04-05",
  reraRegistrationNumber: "K-RERA/PRJ/ERN/104/2024",
  unitNo: "Apartment 9B",
  unitAllocatedDate: "2026-05-10",
  unitAllottedNo: "APT-9B/M-RES",
  carpetAreaSqFt: "1420",
  unitTypeDescription: "Residential 3 BHK luxury apartment with balcony",
  floorNo: "9th Floor",
  towerOrBlock: "Tower Lotus",
  garageClosedParkingNo: "1",
  parkingDetailsText: "Car Parking Bay No. CP-22 located in Basement 1 level",
  commonAreasProRataShare: "0.0095 (0.95% share in basic common elements)",
  totalPriceRupees: "8500000",
  totalPriceWords: "Eighty Five Lakh Rupees",
  ratePerSqFt: "4950",
  breakdownCostCommonAreas: "500000",
  breakdownParkingPrice: "350000",
  breakdownTaxes: "621000",
  breakdownPreferentialCharges: "250000",
  bookingAmountRupees: "850000",
  bookingAmountWords: "Eight Lakh Fifty Thousand Rupees",
  escrowAccountDetails: "State Bank of India, Ernakulam Broadway Branch, Escrow A/c No. 340912839121",
  rebateRatePercent: "8",
  consecutiveDemandsLimit: "3",
  consecutiveMonthsLimit: "2",
  offeredPossessionDays: "15",
  outsideAreasFacilities: "Municipal Link Road and public lighting network",
  outsideCompetentAuthority: "Kochi Municipal Corporation",
  outsideStateActName: "Kerala Apartment Ownership Act, 1983",
  stateActLaws: "Kerala Real Estate (Regulation and Development) Rules, 2018",
  customAgreementTerms: "Clause 34-A: The Allottee shall have the right to request minor interior layout customization, subject to structural engineering approvals and upfront payment of custom fees.",
  priceTableRows: [
    { col1: "Tower Lotus - Apartment 9B (Residential 3BHK)", col2: "Rs. 4,950 / sq. ft" },
    { col1: "Proportionate Common Areas cost", col2: "Rs. 350 / sq. ft" }
  ],
  garageParkingRows: [
    { col1: "Car Parking Bay No. CP-22 (Basement 1)", col2: "Rs. 3,50,000" }
  ],
  plotTableRows: [],
  promoterPhoto: "",
  allotteePhoto: "",
  jointAllotteePhoto: "",
  promoterSignature: "",
  allotteeSignature: "",
  jointAllotteeSignature: "",
  witness1Signature: "",
  witness2Signature: "",
  additionalDisclosures: "The Promoter undertakes that there are no encumbrances, charges, or litigations pending in any court of law regarding the title of the project land.",
  possessionDeadlineDate: "2028-12-31",
  stateApartmentActName: "Kerala Apartment Ownership Act, 1983",
  keralaStampActComplianceConfirmed: true
};

export const sampleIndividualVilla: AgreementDetails = {
  executionDate: "2026-06-10",
  executionPlace: "Trivandrum",
  promoter: {
    type: PromoterType.INDIVIDUAL,
    companyName: "",
    cin: "",
    companiesActYear: "",
    registeredOffice: "",
    pan: "CPKPV2011M",
    authorizedSignatoryName: "",
    signatoryAadhaar: "",
    boardResolutionDate: "",
    partnershipName: "",
    partnershipRegAct: "",
    principalBusinessPlace: "",
    authorizedPartnerName: "",
    partnerAadhaar: "",
    partnerAuthorizedVide: "",
    individualName: "George Mathew Palliparambil",
    individualAadhaar: "3491-0981-8891",
    parentName: "Mathew George",
    age: "58",
    residenceAddress: "Palliparambil Villa, Kazhakkoottam, Thiruvananthapuram, Kerala - 695582"
  },
  allottee: {
    type: AllotteeType.INDIVIDUAL,
    companyName: "",
    cin: "",
    companiesActYear: "",
    registeredOffice: "",
    pan: "DURPK3340L",
    authorizedSignatoryName: "",
    signatoryAadhaar: "",
    boardResolutionDate: "",
    partnershipName: "",
    partnershipRegAct: "",
    principalBusinessPlace: "",
    authorizedPartnerName: "",
    partnerAadhaar: "",
    partnerAuthorizedVide: "",
    individualName: "Dr. Ananya Madhavan",
    individualAadhaar: "8891-2301-4451",
    parentName: "Prof. K. Madhavan",
    age: "36",
    residenceAddress: "Sree Shylam, Medical College Road, Kozhikode, Kerala - 673008",
    hufKartaName: "",
    hufKartaAadhaar: "",
    hufKartaParent: "",
    hufKartaAge: "",
    hufFamilyName: "",
    hufBusinessPlace: "",
    hufPan: ""
  },
  otherAllotteesText: "",
  landOwnerType: "DEVELOPER",
  surveyNumbers: "Survey Nos. 211/2 and 211/4",
  totalAdmeasuringSqM: "2420.00",
  tehsilAndDistrict: "Thiruvananthapuram Taluk, Trivandrum District",
  titleDeedDetails: "Registered Joint Development Agreement dated 14th May 2021 registered as Doc No. 4452/2021",
  subRegistrarOffice: "Sub-Registrar Office, Kazhakkoottam",
  collaborationAgreementDetails: "Co-development agreement executed between Mr. George Mathew and Land-owner Smt. Thankam Mani on 10th May 2021.",
  projectType: ProjectType.PLOTTED_DEVELOPMENT,
  projectComprising: "independent premium garden villas and common private internal roadways",
  otherComponents: "landscaped layout garden, common overhead tank and compound gatehouse",
  projectName: "Mathew Garden Villas Kazhakkoottam",
  commencementAuthority: "Kazhakkoottam Grama Panchayat",
  commencementDate: "2023-09-02",
  commencementBearingNo: "G-PAN/KZT/BLD-112/2023",
  layoutPlanAuthority: "Trivandrum Development Authority (TRIDA)",
  layoutPlanDate: "2023-06-11",
  reraRegOfficePlace: "Trivandrum",
  reraRegDate: "2023-10-18",
  reraRegistrationNumber: "K-RERA/PRJ/TVM/099/2023",
  unitNo: "Villa No. 12",
  unitAllocatedDate: "2026-06-01",
  unitAllottedNo: "VILLA-12/M-GARDENS",
  carpetAreaSqFt: "1850",
  unitTypeDescription: "Premium Duplex Villa - Type B Suite",
  floorNo: "Ground and First Floor",
  towerOrBlock: "Block A",
  garageClosedParkingNo: "2",
  parkingDetailsText: "Double Car Porch adjacent to main portico",
  commonAreasProRataShare: "1/15th equal joint share in Layout Private Roads and common utilities",
  totalPriceRupees: "12500000",
  totalPriceWords: "One Crore Twenty Five Lakh Rupees",
  ratePerSqFt: "5500",
  breakdownCostCommonAreas: "800000",
  breakdownParkingPrice: "400000",
  breakdownTaxes: "950000",
  breakdownPreferentialCharges: "350000",
  bookingAmountRupees: "1250000",
  bookingAmountWords: "Twelve Lakh Fifty Thousand Rupees",
  escrowAccountDetails: "Federal Bank, Kazhakkoottam Branch, RERA Escrow Account No. 10023910023192",
  rebateRatePercent: "7.5",
  consecutiveDemandsLimit: "2",
  consecutiveMonthsLimit: "3",
  offeredPossessionDays: "30",
  outsideAreasFacilities: "Gram Panchayat public drainage channels and outer main pipeline hookups",
  outsideCompetentAuthority: "Kazhakkoottam Grama Panchayat",
  outsideStateActName: "Kerala Co-operative Societies Act",
  stateActLaws: "Kerala Real Estate (Regulation and Development) Rules, 2018",
  customAgreementTerms: "Clause 34-A: Maintenance security deposit of Rupees Fifty Thousand shall be payable to the ad-hoc association at handover.",
  priceTableRows: [],
  garageParkingRows: [],
  plotTableRows: [
    { col1: "Plot No. 12 (Block A Garden Suite)", col2: "Rs. 5,500 / sq. ft" },
    { col1: "Basic Internal Layout Dev levy", col2: "Rs. 450 / sq. ft" }
  ],
  promoterPhoto: "",
  allotteePhoto: "",
  jointAllotteePhoto: "",
  promoterSignature: "",
  allotteeSignature: "",
  jointAllotteeSignature: "",
  witness1Signature: "",
  witness2Signature: "",
  additionalDisclosures: "Subject to standard local village office thandaper certificate updates and mutate tax receipts.",
  possessionDeadlineDate: "2027-12-31",
  stateApartmentActName: "Kerala Co-operative Societies Act & local village regulations",
  keralaStampActComplianceConfirmed: true
};
