// Form section for each editable preview value; nested and repeated fields use their root key.
const fieldSteps: Record<string, number> = {
  "promoterCompany.name": 1,
  "promoterCompany.cin": 1,
  "promoterCompany.pan": 1,
  "promoterCompany.registeredOffice": 1,
  "promoterCompany.corporateOffice": 1,
  "promoterCompany.authorizedSignatory": 1,
  "promoterCompany.signatoryAadhaar": 1,
  "promoterCompany.boardResolutionDate": 1,
  "promoterPartnership.name": 1,
  "promoterPartnership.businessPlace": 1,
  "promoterPartnership.pan": 1,
  "promoterPartnership.authorizedPartner": 1,
  "promoterPartnership.partnerAadhaar": 1,
  "promoterPartnership.authorizedVide": 1,
  "promoterIndividual.name": 1,
  "promoterIndividual.aadhaar": 1,
  "promoterIndividual.pan": 1,
  "promoterIndividual.parentType": 1,
  "promoterIndividual.parentName": 1,
  "promoterIndividual.age": 1,
  "promoterIndividual.residing": 1,
  "landOwnerEntries": 3,
  "landJDA": 3,
  "projectType": 3,
  "projectTypeOther": 3,
  "projectName": 3,
  "projectBuildingType": 3,
  "projectBuildingTypeOther": 3,
  "projectComprising": 3,
  "projectOtherComponents": 3,
  "plotOtherComponents": 3,
  "commencementAuthority": 4,
  "commencementDate": 4,
  "commencementNo": 4,
  "layoutAuthority": 4,
  "additionalDisclosures": 4,
  "priceBreakdown": 5,
  "garageDetails": 5,
  "plotPricing": 5,
  "paymentFavourOf": 5,
  "paymentPayableAt": 5,
  "competentAuthorityForDeclaration": 5,
  "relevantStateAct": 5,
  "possessionTargetMonth": 6,
  "gracePeriodDays": 6,
  "encumbranceDetails": 6,
  "defaultConsecutiveDemands": 6,
  "defaultConsecutiveMonths": 6,
  "maintenanceClauses": 6,
  "placeOfExecution": 6,
  "placeOfDeemedExecution": 6,
  "additionalTerms": 6
};

export function getAgreementFieldStep(field: string): number | undefined {
  return fieldSteps[field] ?? fieldSteps[field.split(".")[0]];
}
